from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any


def _notebook_markdown_cell(source: str) -> dict[str, Any]:
    """
    Create a markdown cell for a Jupyter notebook.
    """
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source,
    }


def _notebook_code_cell(source: str) -> dict[str, Any]:
    """
    Create a code cell for a Jupyter notebook.
    """
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def save_notebook_artifact(
    *,
    participant: str,
    session: str,
    notebook_dir: Path,
    report_dir: Path,
    diagnostic_dir: Path,
    plot_dir: Path,
    filename: str,
    report_filename: str,
    diagnostics_filename: str,
) -> Path:
    """
    Save a Jupyter notebook that documents the manual validation test.
    """
    notebook_dir.mkdir(parents=True, exist_ok=True)

    output_path = notebook_dir / filename
    generated_at = datetime.now().isoformat(timespec="seconds")

    report_path = report_dir / report_filename
    diagnostics_path = diagnostic_dir / diagnostics_filename
    plot_paths = sorted(plot_dir.glob("*.png"))

    cells: list[dict[str, Any]] = []

    cells.append(
        _notebook_markdown_cell(
            "# Fitts Data Framework Validation Report\n\n"
            f"- Participant: `{participant}`\n"
            f"- Session: `{session}`\n"
            f"- Generated at: `{generated_at}`\n\n"
            "This notebook was generated automatically by the manual "
            "`fitts_data` framework test script. It collects the saved "
            "session report, diagnostics and validation plots in one document."
        )
    )

    cells.append(
        _notebook_markdown_cell(
            "## 1. Purpose of the Validation Notebook\n\n"
            "This notebook documents the output of a manual smoke test for the "
            "`fitts_data` framework. The test verifies that database access, "
            "metric extraction, summaries, regression, quality analysis, "
            "interaction-level analysis, diagnostics and plotting functions "
            "can be executed for one selected participant/session pair."
        )
    )

    if report_path.exists():
        report_content = report_path.read_text(encoding="utf-8")

        cells.append(
            _notebook_markdown_cell(
                "## 2. Session Report\n\n"
                f"{report_content}"
            )
        )
    else:
        cells.append(
            _notebook_markdown_cell(
                "## 2. Session Report\n\n"
                "No session report file was found."
            )
        )

    cells.append(
        _notebook_markdown_cell(
            "## 3. Diagnostic JSON\n\n"
            "The structured diagnostic output is stored as a JSON artifact. "
            "The following code cell can be executed to inspect it."
        )
    )

    diagnostics_relative_path = (
        Path("../diagnostics") / diagnostics_filename
    ).as_posix()

    cells.append(
        _notebook_code_cell(
            "from pathlib import Path\n"
            "import json\n\n"
            f"diagnostics_path = Path({diagnostics_relative_path!r})\n"
            "diagnostics = json.loads(\n"
            "    diagnostics_path.read_text(encoding='utf-8')\n"
            ")\n\n"
            "diagnostics.keys()"
        )
    )

    cells.append(
        _notebook_markdown_cell(
            "## 4. Saved Validation Plots\n\n"
            "The following plots were generated by the test script and saved "
            "as PNG files."
        )
    )

    if plot_paths:
        for plot_path in plot_paths:
            relative_plot_path = (
                Path("../plots") / plot_path.name
            ).as_posix()

            title = plot_path.stem.replace("_", " ").title()

            cells.append(
                _notebook_markdown_cell(
                    f"### {title}\n\n"
                    f"![{title}]({relative_plot_path})"
                )
            )
    else:
        cells.append(
            _notebook_markdown_cell(
                "No plot files were found."
            )
        )

    cells.append(
        _notebook_markdown_cell(
            "## 5. Interpretation Note\n\n"
            "The notebook is intended as a validation artifact. It does not "
            "replace the scientific interpretation in the thesis, but it "
            "documents that the framework can load, analyse, diagnose and "
            "visualise the selected session."
        )
    )

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "pygments_lexer": "ipython3",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    output_path.write_text(
        json.dumps(
            notebook,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    print(f"Saved notebook: {output_path}")

    return output_path